name: Git History

on: pull_request

permissions:
  contents: read

jobs:
  clean:
    name: Clean
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/developerc286/clean_git_history:v1.0.4@sha256:5783341a3377a723e409e72b9ec0826a75ba944288d030978355de05ef65b186
    steps:
      - name: Checkout code.
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Check clean Git history.
        run: clean_git_history "origin/${{ github.base_ref }}"
