name: Git History

on: pull_request

permissions:
  contents: read

jobs:
  clean:
    name: Clean
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/developerc286/clean_git_history:1.1.0@sha256:d61b1c1627513f43760c86c63515fc8b8d97879d9b1401dadc24d7f18dd903d3
    steps:
      - name: Checkout code.
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Check clean Git history.
        run: clean_git_history --verbose "origin/${{ github.base_ref }}"
