name: Git History

on: pull_request

env:
  # Forcing Earthly to use colours, to make reading output easier.
  FORCE_COLOR: 1

jobs:
  clean:
    name: Clean
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Checkout code.
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Check clean Git history.
        run: make check-clean-git-history FROM="origin/${{ github.base_ref }}"
